### ISSUE TITLE
Returning array from query to XML data

### ISSUE THREAD

**Issue by nnita** [Athari/YaLinqo#14]
after a consultation with linq I present a problem to return the object, which returns me is a structure that can not handle

```php
$xml =  from($array)
    ->select('$s ==>$s["PricedItineraries"]["PricedItinerary"]')
    ->orderBy('$s ==> $s["AirItineraryPricingInfo"]["ItinTotalFare"]["TotalFare"]
        ["@attributes"]["Amount"]')
    ->thenBy('$s ==> $s["AirItinerary"]["OriginDestinationOptions"]
        ["OriginDestinationOption"]["FlightSegment"]
        ["TPA_Extensions"]["ValidateAirline"]');
```

return 

```php
object(YaLinqo\OrderedEnumerable)#2294 (6) {
  ["source":"YaLinqo\OrderedEnumerable":private]=>
  object(YaLinqo\Enumerable)#2292 (1) {
    ["getIterator":"YaLinqo\Enumerable":private]=>
    object(Closure)#2293 (2) {
      ["static"]=>
      array(3) {
        ["self"]=>
        object(YaLinqo\Enumerable)#2282 (1) {
          ["getIterator":"YaLinqo\Enumerable":private]=>
          object(Closure)#2283 (1) {
            ["static"]=>
            array(1) {
              ["it"]=>
              object(ArrayIterator)#2281 (1) {
                ["storage":"ArrayIterator":private]=>
                array(3) {
```

the problem is I can not iterate over the object

but if I put `toArray()` get an error with the index and returns null

**Comment by Athari** [comment]
Obviously, some array index in one of your long chains of array indexes is missing. You should inspect the objects you receive and check what index is missing, then adjust your code appropriately. To improve debugging experience, you can change string lambdas to anonymous functions. I can suggest two ways.

### 1. Full index chains

```php
$array = from($xml)
    ->select(function ($s) {
        return $s["PricedItineraries"]["PricedItinerary"];
    })
    ->orderBy(function ($s) {
        return $s["AirItineraryPricingInfo"]["ItinTotalFare"]
            ["TotalFare"]["@attributes"]["Amount"];
    })
    ->thenBy(function ($s) {
        return $s["AirItinerary"]["OriginDestinationOptions"]
            ["OriginDestinationOption"]["FlightSegment"]
            ["TPA_Extensions"]["ValidateAirline"];
    });
```

This way, you'll be able to put breakpoints inside functions and inspect the received objects. If your IDE supports it, it'll also stop on the line which can't find the index you need.

### 2. Simplified index chains

```php
$array = from($xml)
    ->select(function($s) {
        $s = $s["PricedItineraries"];
        $s = $s["PricedItinerary"];
        return $s;
    })
    ->orderBy(function($s) {
        $s = $s["AirItineraryPricingInfo"];
        $s = $s["ItinTotalFare"];
        $s = $s["TotalFare"];
        $s = $s["@attributes"];
        $s = $s["Amount"];
        return $s;
    })
    ->thenBy(function($s) {
        $s = $s["AirItinerary"];
        $s = $s["OriginDestinationOptions"];
        $s = $s["OriginDestinationOption"];
        $s = $s["FlightSegment"];
        $s = $s["TPA_Extensions"];
        $s = $s["ValidateAirline"];
        return $s;
    });
```

Now you'll also see the exact line which fails. Stack trace of the exception/error will contain the line number and in this case every line contains just one index which can fail. (Usually you don't need to write code like this, but it can help during debugging.)

### General

If you iterate over the returned object using `foreach` later in the code, calling `toArray` is unnecessary. In this case, the only difference is when you receive the error. Evaluation of the sequence is lazy, so without `toArray` not creation of the sequence will fail, but iteration over it (in `foreach`).

`toArray` will convert the iterator into plain old array, which can be helpful for serialization, debugging, passing into code which expects arrays etc.

If you need further assistance, you'll need to provide source data (so I could reproduce the problem) and exact error message with stack trace — after you apply one of the suggested modifications.

P. S. Your variable names look suspicious, by the way. Your code suggests the first line should be `$array =  from($xml)`, not `$xml =  from($array)`, considering you seem to be inspecting SimpleXML attributes.
