### ISSUE TITLE
Using YaLinqo with Slim Framework

### ISSUE THREAD

**Issue by RODOBTA** [Athari/YaLinqo#31]
I have not been able to add the library to a Slim project and be able to use it. Somebody made it?

**Comment by Athari** [comment]
@RODOBTA 
What are your problems exactly? Show your code, error messages you receive etc.

**Comment by RODOBTA** [comment]
@Athari 
It does not generate any error, it just returns an empty object, I do not know if I'm missing any reference, or upload a file

My code:
![image](https://user-images.githubusercontent.com/12815795/38771429-f7c6d388-3fe8-11e8-82a0-bd3feea882fe.png)

My references:
![image](https://user-images.githubusercontent.com/12815795/38771432-0a6c5d50-3fe9-11e8-9a8c-12c8a4693009.png)

Result:
![image](https://user-images.githubusercontent.com/12815795/38771451-2180e894-3fe9-11e8-9c86-9ae7f94aa6a1.png)

If I omit the part of the first image, this is the result:
![image](https://user-images.githubusercontent.com/12815795/38771466-71cb0a6e-3fe9-11e8-8f8a-f30aa6a0d3c4.png)

**Comment by Athari** [comment]
@RODOBTA 
Not sure what IDE you're using and how "Pretty" works, but if you switch to "Raw" you'll probably see that you're inspecting an iterator class (`Enumerable`) with private fields. As getting values from iterators changes their state, IDEs can't display their contents in a nice way without breaking the code.

In general, YaLinqo produces iterators, not pure arrays. You need to iterate over them with `foreach` (preferable) or convert them to arrays or some other format (using `toList`, `toArray`, `toDictionary`, `toJSON` etc.) or reduce them to single values (`min`, `max` etc.).

If the code you quoted is used by a method which expects arrays (I don't know how Slim works), then you can append `->toList()` to your method chain:

```php
return from($result)->where(function($item) { return $item['Id'] == 0; })->toList();
```

That would also allow IDE on inspect the result.

**Comment by RODOBTA** [comment]
Using Visual Studio Code, add the .toList () to the end, but I get an error
This is my code:
![image](https://user-images.githubusercontent.com/12815795/38783038-64ae2f62-40c2-11e8-934c-b47c4ed07e58.png)

These are my data:
![image](https://user-images.githubusercontent.com/12815795/38783057-b48cad4c-40c2-11e8-8fc3-7749c7217870.png)

What I want to get from $result, are the items that have Padre= 0

**Comment by Athari** [comment]
@RODOBTA 
1. I don't see `->toList()` in your code.
2. I don't see the error you receive.
3. Items of your `$result` array seem to be objects, not arrays, so `$item['Padre']` syntax isn't supposed to work (members are accessed with `->` operator).

**Comment by RODOBTA** [comment]
@Athari 
I have modified the form of access to the property, and add the toList ():
![image](https://user-images.githubusercontent.com/12815795/38783235-136edc34-40c5-11e8-833a-6021ebba6cf4.png)

this is the error that I receive
![image](https://user-images.githubusercontent.com/12815795/38783241-36e3f456-40c5-11e8-8cff-1d9901fca7ca.png)

**Comment by Athari** [comment]
@RODOBTA 
Class members in PHP are accessed using `->` operator, not `.`. You need to write `->toList()`, not `.toList()`.

**Comment by RODOBTA** [comment]
@Athari 
It worked perfect, I had not noticed the error in .toList (), replaced by -> toList () now it works great. Thank you very much.
