### ISSUE TITLE
Distinct exception cases should have distinct exception types

### ISSUE THREAD

**Issue by Bilge** [Athari/YaLinqo#37]
`single()` currently throws `UnexpectedValueException` for two distinct cases:

1. The case where there are no matches, as well as
2. the case where there are too many matches.

It is still possible to distinguish these exception cases by exception message, but it is preferable to catch different types rather than inspect the message because messages are subject to change and type comparison is faster, more succinct to write and clearer.

**Comment by Athari** [comment]
Exceptions are for exceptional behavior, not for normal control flow. If you handle these cases differently, it means that they're not exceptions, but regular cases. Consider using `singleOrDefault` (it returns the only element of a sequence, or a default value if the sequence contains no elements) or some combination of `first`, `firstOrDefault`, `count` etc., depending on what cases your code handles.

Exceptions are very expensive and handling them requires complex syntax. Don't use them for control flow.

**Comment by Bilge** [comment]
That's a good point, and I probably do want `singleOrDefault()` here. However, this does not invalidate the point that distinct exception types should be thrown instead of shared between different cases.
