### ISSUE TITLE
Enumerable::getIterator fails silently

### ISSUE THREAD

**Issue by oojacoboo** [Athari/YaLinqo#53]
For some reason, when calling `toArray`, which called `getIterator`, the script is failing silently.  I've confirmed the array being passed to `from` is okay.  It is a fairly deeply nested array with many objects.

I guess the real question here is... what's preventing exceptions?

**Comment by oojacoboo** [comment]
I'm going to close this because I'm not absolutely certain how the error was getting stomped out.  Although, there was a method not found issue within the callback for the iterator.

**Comment by Athari** [comment]
If you can create a minimum example that reproduces the problem, it would be great.

Please note that if you're using new PHP, you'll face #25. I'm terribly sorry about the state of the issue. At the moment you can comment out the line with `create_function` if it's causing issues.
