### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by oojacoboo** [Athari/YaLinqo#57]
Is there any motivation from the maintainers to continue this lib?  As it currently stands there are PHP 8 and 8.1 issues.  PHP 7.4 is only receiving security support and that's expiring in 11 months.  PHP 7.3 is EOL in 3 days, no longer receiving any security updates.

**Comment by Athari** [comment]
This has been discussed in detail in #24.

Essentially, if you don't plan to use lambdas, just comment out the "obsolete" line of code, everything else works fine.
